# Generated by Django 2.0 on 2017-12-22 23:03

from django.db import migrations, models
import tweets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_tweet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=256, validators=[tweets.validators.validate_content]),
        ),
    ]
