# Generated by Django 2.0 on 2017-12-31 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_auto_20171230_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='patent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.Tweet'),
        ),
    ]
