# Generated by Django 2.0 on 2017-12-31 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_tweet_patent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='patent',
            new_name='parent',
        ),
    ]
